first_site/first_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('fibonacci/', include('fibonacci.urls')),
    # path('collatz/',include('collatz.urls')),
    # path('password/',include('password.urls')),
    path('student/',include('student.urls')),
]

first_site/menu/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('home', views.index, name='index'),
]

first_site/shops/urls.py
from django.urls import path
from . import views
# from django.contrib.auth import views as auth_views

app_name='shops'

urlpatterns = [
    # path('<int:id>', views.product_detail, name='product_detail'),
    path('', views.products_list, name='products_list'),
    path('login', views.login_, name='login'),
    path('logout', views.logout_, name='logout'),
    path('cart',views.view_cart,name='cart'),
    path('cart/add/<int:product_id>',views.add_to_cart,name='add_cart')

]

first_site/shops/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Products(models.Model):
    img = models.URLField(max_length=256, null=True)
    name = models.CharField(max_length=256)
    cost = models.DecimalField(max_digits=10, decimal_places=2)

    def _str_(self):
        return f'{self.img}: {self.name} - {self.cost}'
    
class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    
class Category(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name
  
  

first_site/shops/views.py
from django.shortcuts import render, redirect
from .models import Products
from django.contrib.auth.decorators import permission_required
from django.contrib.auth import authenticate, login, logout
from.models import  Products,Category,CartItem

# Create your views here.

# def product_detail(request, id):
#     product = Products.objects.get(id = id)
#     return render(request, 'eapp/product_detail.html', {'product': product})
def products_list(request):
    products = Products.objects.all()
    return render(request, 'shops/temp.html', {'products': products})

def login_(request):
    if request.method == 'GET':
        return render(request, 'shops/authenticate.html')
    if request.method == 'POST':
        username_ = request.POST.get('username', '')
        entered_password = request.POST.get('password', '')
        user = authenticate(username=username_, password=entered_password)
        print(user)
        if user is not None:
            login(request, user)
        return redirect('products_list')

def logout_(request):
    logout(request)
    return redirect('shops:login_')

@permission_required('shops.add_cartitem', login_url='shops:login')
def add_to_cart(request, product_id):
    product_ = Products.objects.get(pk=product_id)
    try:
        cartitem = CartItem.objects.get(product=product_, user=request.user)
    except CartItem.DoesNotExist:
        CartItem.objects.create(
            product=product_,
            user=request.user)
    cartitem, created = CartItem.objects.get_or_create(product=product_, user=request.user)
    cartitem.quantity += 1
    cartitem.save()
    return redirect('shops:cart')

@permission_required('shops.view_cartitem',login_url='shops:login')
def view_cart(request):
    cartitems = CartItem.objects.filter(user=request.user)
    return render(request, 'shops/cart.html', {'cartitems': cartitems})

first_site/shops/templates/shops/authenticate.html
<!DOCTYPE html>
<html>
    <body>
        <form method="POST" action="{% url 'shops:login' %}">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" id="username" name="username">
            <label for="password">Password</label>
            <input type="password" id="password" name="password">
            <input type="submit" value="Login">
        </form>
    </body>
</html>

first_site/shops/templates/shops/cart.html
<!DOCTYPE html>
<html>
    <body>
        {% for item in cartitems %}
        <p>{{item.product}} - {{item.quantity}}</p>
        {% endfor %}
    </body>
</html>

first_site/shops/templates/shops/temp.html
<!doctype html>
<html lang="en">
{% if not user.is_authenticated %}
<h3>Requires password, authenticate yourself <a href="{% url 'login' %}">here</a>.</h3>
{% else %}

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>eapp</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
        <a class="Home">Home</a>
        <form class="form-inline" action="cart.html">
          <a href="{% url 'shops:logout' %}">Logout</a> &nbsp;&nbsp;&nbsp;
          <a class="cart mr-sm-2" type="cart">Cart</a>
        </form>
      </nav>
      <h1 style="text-align: center; color: blue;">SHOP</h1>
  <div class = "row">
      {% for product in products %}
      <div class="card text-center" style="width: 18rem; margin: 15px ; align-items: center;padding-top : 10px;">
        <img src= "{{product.img}}" class="card-img-top" alt="..." style="height: 200px; width: 200px;">
        <div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <p class="card-text" style="text-align: center;">Rs.{{product.cost}}</p>
          <form action="{% url 'shops:add_cart' product.id %}">
            <input type="submit" value="Add to Cart">
        </form>
        </div>
      </div>
    {% endfor %}
  </div>

{% endif %}


  
      

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>