first_site/ecommerce/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name='shop'

urlpatterns = [
    path('home', views.product_list, name='home'),
    path('cart/add/<int:product_id>', views.add_to_cart, name='add_cart'),
    path('cart', views.view_cart, name='cart'),
    path('login', auth_views.LoginView.as_view(template_name='ecommerce/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout')
]

first_site/first_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('fibonacci/', include('fibonacci.urls')),
    # path('collatz/',include('collatz.urls')),
    # path('password/',include('password.urls')),
    path('student/',include('student.urls')),
]

first_site/menu/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('home', views.index, name='index'),
]

first_site/ecommerce/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name

class Product(models.Model):
    img = models.URLField(max_length=256, null=True)
    name = models.CharField(max_length=256)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

first_site/ecommerce/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from .models import Product, Category, CartItem

# Create your views here.

def product_list(request):
    products = Product.objects.all()
    return render(request, 'ecommerce/home.html', {'products': products})

@permission_required('ecommerce.add_cartitem', login_url='shop:login')
def add_to_cart(request, product_id):
    product_ = Product.objects.get(pk=product_id)
    try:
        cartitem = CartItem.objects.get(product=product_, user=request.user)
    except CartItem.DoesNotExist:
        CartItem.objects.create(
            product=product_,
            user=request.user)
    cartitem, created = CartItem.objects.get_or_create(product=product_, user=request.user)
    cartitem.quantity += 1
    cartitem.save()
    return redirect('shop:cart')

@permission_required('shop.view_cartitem',login_url='shop:login')
def view_cart(request):
    cartitems = CartItem.objects.filter(user=request.user)
    return render(request, 'ecommerce/cart.html', {'cartitems': cartitems})

first_site/ecommerce/templates/ecommerce/cart.html
<!DOCTYPE html>
<html>
    <body>
        {% for item in cartitems %}
        <p>{{item.product}} - {{item.quantity}}</p>
        {% endfor %}
    </body>
</html>

first_site/ecommerce/templates/ecommerce/home.html
<!DOCTYPE html>
<html>
    <body>
        <h2>SHOP</h2>
        {% for product in products %}
        <p>{{product.name}}</p>
        <p>{{product.category}}</p>
        <p>{{product.price}}</p>
        <br/><br/><br/>
        <form action="{% url 'shop:add_cart' product.id %}">
            <input type="submit" value="Add to Cart">
        </form>
        {% endfor %}
        
    </body>
</html>

first_site/ecommerce/templates/ecommerce/login.html
{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'shop:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>
{% endblock %}